volumes:
  data:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      app_net:
        ipv4_address: ${IP_MONGODB_SERVER}
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: ${IP_API_SERVER}
  gui:
    container_name: gui
    build:
      context: .
      dockerfile: ./Dockerfile.gui
    ports:
      - 8080:8080
    networks:
      app_net:
        ipv4_address: ${IP_GUI_SERVER}

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}
